// Generated by CoffeeScript 1.5.0
(function() {
  'use strict';
  var checkLinkTo, switchToPage;

  $.fn.extend({
    hideDetails: function() {
      return $(this).each(function() {
        $(this).addClass('collapsed').prev().removeClass('last-child');
        return $(this).next().removeClass('first-child');
      });
    },
    showDetails: function() {
      return $(this).each(function() {
        $(this).removeClass('collapsed').siblings().hideDetails();
        $(this).prev().addClass('last-child');
        return $(this).next().addClass('first-child');
      });
    }
  });

  switchToPage = function(page) {
    page = $(page);
    page.show().siblings('.page').hide();
    $("#appNavbar a[href=#" + (page.attr('id')) + "]").parent().addClass('selected').siblings().removeClass('selected');
    return page;
  };

  checkLinkTo = function(link) {
    var href, itsPage, targetElem;
    href = $(link).attr('href');
    if (href[0] !== '#') {
      return href;
    } else {
      targetElem = $(href);
      if (targetElem.hasClass('page')) {
        itsPage = targetElem;
      } else {
        itsPage = targetElem.parents('.page');
      }
      if (itsPage.length > 0) {
        switchToPage(itsPage);
      }
      return itsPage;
    }
  };

  $(function() {
    $('.page').hide();
    $('a').click(function() {
      return checkLinkTo(this);
    });
    $('#appNavbar a').eq(0).click();
    return $('.monster-info').hideDetails().click(function() {
      console.log('clicked');
      return $(this).showDetails();
    });
  });

}).call(this);
