// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  requirejs.config({
    baseUrl: 'js',
    paths: {
      lib: '../lib',
      tmpl: '../tmpl'
    }
  });

  requirejs(['lib/jquery/jquery', 'lib/underscore/underscore', 'lib/backbone/backbone', 'lib/backbone/backbone-relational', 'data']);

}).call(this);
